INSERT INTO financial_categories (name, icon, color, owner_user_id) VALUES
('Alimentación', 'Utensils', '#EF4444', NULL),
('Supermercado', 'ShoppingCart', '#F97316', NULL),
('Transporte', 'Car', '#EAB308', NULL),
('Vivienda', 'Home', '#22C55E', NULL),
('Servicios Básicos', 'Lightbulb', '#06B6D4', NULL),
('Salud y Bienestar', 'HeartPulse', '#EC4899', NULL),
('Educación', 'GraduationCap', '#8B5CF6', NULL),
('Entretenimiento', 'Ticket', '#D946EF', NULL),
('Ropa y Calzado', 'Shirt', '#A855F7', NULL),
('Cuidado Personal', 'Scissors', '#F43F5E', NULL),
('Mascotas', 'Dog', '#84CC16', NULL),
('Ahorros e Inversiones', 'PiggyBank', '#10B981', NULL),
('Salario', 'Banknote', '#14B8A6', NULL),
('Transferencias', 'ArrowRightLeft', '#64748B', NULL),
('Viajes', 'Plane', '#0EA5E9', NULL),
('Seguros', 'ShieldCheck', '#3B82F6', NULL),
('Regalos y Donaciones', 'Gift', '#F43F5E', NULL),
('Suscripciones', 'Repeat', '#6366F1', NULL),
('Impuestos', 'FileText', '#94A3B8', NULL),
('Otros', 'HelpCircle', '#CBD5E1', NULL);
